services:
  authorization_server_db:
    container_name: "authorization_server_dev_db"
    image: postgres:16.1
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  session_cache:
    container_name: "redis_session_cache"
    image: redis:7.2.4
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6380:6379