services:
  authorization_server_db:
    container_name: "authorization_server_db"
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "${SSO_STORE_PATH}/pgdata:/var/lib/postgresql/data/pgdata"
  session_cache:
    container_name: "redis_session_cache"
    image: redis:${REDIS_VERSION}
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD}"
  authorization_server:
    container_name: "oauth2_authorization_server"
    image: oauth2/authorization-server:${OAUTH2_SERVER_VERSION}
    restart: always
    depends_on:
      - authorization_server_db
      - session_cache
    environment:
      DATASOURCE_URL: "jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}"
      DATASOURCE_USERNAME: "${DB_USERNAME}"
      DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      OAUTH2_CLIENT_ID: "${OAUTH2_SERVER_CLIENT_ID}"
      OAUTH2_CLIENT_SECRET: "${OAUTH2_SERVER_CLIENT_SECRET}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      BASE_URL: "${OAUTH2_SERVER_BASE_URL}"
      JAVA_OPTS: "-Djavax.net.ssl.trustStore=${OAUTH2_SERVER_TRUSTSTORE_INTERNAL_PATH} -Djavax.net.ssl.trustStorePassword=${OAUTH2_SERVER_TRUSTSTORE_PASSWORD}"
    links:
      - authorization_server_db:postgreshost
      - session_cache:redishost
    volumes:
      - "${NGINX_CERTS_PATH}/cert.p12:${OAUTH2_TRUSTSTORE_INTERNAL_PATH}:ro"
  gateway:
    container_name: "oauth2_server_gateway"
    image: nginx:${NGINX_VERSION}
    restart: always
    depends_on:
      - authorization_server
    environment:
      OAUTH2_SERVER_PORT: ${OAUTH2_SERVER_EXTERNAL_PORT}
    ports:
      - ${OAUTH2_SERVER_EXTERNAL_PORT}:${OAUTH2_SERVER_EXTERNAL_PORT}
    volumes:
      - "${NGINX_CERTS_PATH}:/home/certs:ro"
      - "${NGINX_CONFIGS_PATH}:/etc/nginx/templates:ro"
    links:
      - authorization_server:oauth2-authorization-server